name: javascript tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "javascript"
    strategy:
      matrix:
        node: ["12", "14", "16", "17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: |
          npm ci
      - name: Test with jest
        run: |
          npm run testESModule
